### ISSUE TITLE
echo $FOO not working

### ISSUE THREAD

**Issue by BinaryShrub** [toddbluhm/env-cmd#93]
I'm trying to use cmd-env to help templatize my aws calls from yarn but I'm not able to get the variables...

for example
`npx env-cmd -e production echo $FOO` returns nothing when I'd expect it to return `BAR`

but `npx env-cmd -e production printenv FOO` returns `BAR`

How can I access to the env vars so I can pipe them into other commands as parameters?

**Comment by BinaryShrub** [comment]
The only solution I have as of now is to do something like so:
```
echo $(npx env-cmd -e production printenv FOO)
```

but as you can imagine if there are multiple variables I need, this command gets really long

**Comment by toddbluhm** [comment]
see response here: https://github.com/toddbluhm/env-cmd/issues/91#issuecomment-548672584

**Comment by toddbluhm** [comment]
I have published `10.1.0` that now includes support for expanding env vars in arguments using the `-x` flag and the format `$var`.

**Comment by yatharth** [comment]
`npx env-cmd -x --use-shell 'echo $FOO'` still doesn’t seem to be working with version 10.1.0.

Is this expected?

![image](https://user-images.githubusercontent.com/1520684/147415040-83d8ea1f-ed29-4439-ba5b-66d2c22b8636.png)
